--Creates Tables to load the Data into the Database.
--From this we create our other Tables that we need in our DB
--These Tables are without Foreign Key Constraints, sometimes without Primary Constraints


--Creates Table for the Corona Data --> Final Table for Relation CoronaData
CREATE TABLE CoronaData (
	Corona_ID INTEGER,
	Date DATE,
	State VARCHAR(255), 
	tot_cases INTEGER,
	conf_cases FLOAT,
	prob_cases FLOAT,
	new_case INTEGER,
	pnew_case FLOAT,
	tot_death INTEGER,
	conf_death FLOAT,
	prob_death FLOAT,
	new_death INTEGER,
	pnew_death FLOAT,
	created_at VARCHAR(255),
	consent_cases VARCHAR(255),
	consent_deaths VARCHAR(255),

	PRIMARY KEY (Corona_ID)
);

--Creates Table for the Vaccination Data --> Final Table
create table CoronaVax (
    CoronaVaxID INTEGER,
    Date DATE,
    Location VARCHAR(255),
    Demographic_Category VARCHAR(255),
    census FLOAT,
    Administered_Dose1 FLOAT,
    Series_Complete_Yes FLOAT,
    Booster_Doses FLOAT,
    Second_Booster FLOAT,
    Administered_Dose1_pct_agegroup FLOAT,
    Series_Complete_Pop_pct_agegroup FLOAT,
    Booster_Doses_Vax_pct_agegroup FLOAT,
    Second_Booster_Vax_pct_agegroup FLOAT,

    PRIMARY KEY(coronaVaxID)
);

--Creates Table for Employment --> Final Table for Relation Employment
CREATE TABLE Employment (
	Employment_ID INTEGER,
	Fulltime INTEGER,
	Parttime INTEGER,
	Grand_Total INTEGER,
	Date DATE,

	PRIMARY KEY (Employment_ID)
);

--Creates Table for FlightDataSet -> From this create FlighDataSet related Tables
CREATE TABLE FlightDataSet (
	Year                            INTEGER,
    Quarter                         INTEGER,
    Month                           INTEGER,
    DayofMonth                      INTEGER,
    DayOfWeek                       INTEGER,
    FlightDate                      DATE,
    Reporting_Airline               VARCHAR(255),
    DOT_ID_Reporting_Airline        INTEGER,
    IATA_CODE_Reporting_Airline     VARCHAR(255),
    Tail_Number                     VARCHAR(255),
    Flight_Number_Reporting_Airline INTEGER,
    OriginAirportID                 INTEGER,
    OriginAirportSeqID              INTEGER,
    OriginCityMarketID              INTEGER,
    Origin                          VARCHAR(255),
    OriginCityName                  VARCHAR(255),
    OriginState                     VARCHAR(255),
    OriginStateFips                 INTEGER,
    OriginStateName                 VARCHAR(255),
    OriginWac                       INTEGER,
    DestAirportID                   INTEGER,
    DestAirportSeqID                INTEGER,
    DestCityMarketID                INTEGER,
    Dest                            VARCHAR(255),
    DestCityName                    VARCHAR(255),
    DestState                       VARCHAR(255),
    DestStateFips                   INTEGER,
    DestStateName                   VARCHAR(255),
    DestWac                         FLOAT,
    CRSDepTime                      FLOAT,
    DepTime                         FLOAT,
    DepDelay                       	FLOAT,
    DepDelayMinutes                	FLOAT,
    DepDel15                       	FLOAT,
    DepartureDelayGroups            FLOAT,
    DepTimeBlk                      VARCHAR(255),
    TaxiOut                        	FLOAT,
    WheelsOff                       FLOAT,
    WheelsOn                        FLOAT,
    TaxiIn                         	FLOAT,
    CRSArrTime                      FLOAT,
    ArrTime                         FLOAT,
    ArrDelay                       	FLOAT,
    ArrDelayMinutes                	FLOAT,
    ArrDel15                       	FLOAT,
    ArrivalDelayGroups              FLOAT,
    ArrTimeBlk                      VARCHAR(255),
    Cancelled                      	FLOAT,
    CancellationCode                VARCHAR(255),
    Diverted                       	FLOAT,
    CRSElapsedTime                 	FLOAT,
    ActualElapsedTime              	FLOAT,
    AirTime                        	FLOAT,
    Flights                        	FLOAT,
    Distance                       	FLOAT,
    DistanceGroup                   FLOAT,
    CarrierDelay                   	FLOAT,
    WeatherDelay                   	FLOAT,
    NASDelay                       	FLOAT,
    SecurityDelay                  	FLOAT,
    LateAircraftDelay              	FLOAT,
    FirstDepTime                    VARCHAR(255),
    TotalAddGTime                   VARCHAR(255),
    LongestAddGTime                 VARCHAR(255),
    DivAirportLandings              FLOAT,
    DivReachedDest                  VARCHAR(255),
    DivActualElapsedTime            VARCHAR(255),
    DivArrDelay                     VARCHAR(255),
    DivDistance                     VARCHAR(255),
    Div1Airport                     VARCHAR(255),
    Div1AirportID                   VARCHAR(255),
    Div1AirportSeqID                VARCHAR(255),
    Div1WheelsOn                    VARCHAR(255),
    Div1TotalGTime                  VARCHAR(255),
    Div1LongestGTime                VARCHAR(255),
    Div1WheelsOff                   VARCHAR(255),
    Div1TailNum                     VARCHAR(255),
    Div2Airport                     VARCHAR(255),
    Div2AirportID                   VARCHAR(255),
    Div2AirportSeqID                VARCHAR(255),
    Div2WheelsOn                    VARCHAR(255),
    Div2TotalGTime                  VARCHAR(255),
    Div2LongestGTime                VARCHAR(255),
    Div2WheelsOff                   VARCHAR(255),
    Div2TailNum                     VARCHAR(255),
    Div3Airport                     VARCHAR(255),
    Div3AirportID                   VARCHAR(255),
    Div3AirportSeqID                VARCHAR(255),
    Div3WheelsOn                    VARCHAR(255),
    Div3TotalGTime                  VARCHAR(255),
    Div3LongestGTime                VARCHAR(255),
    Div3WheelsOff                   VARCHAR(255),
    Div3TailNum                     VARCHAR(255),
    Div4Airport                     VARCHAR(255),
    Div4AirportID                   VARCHAR(255),
    Div4AirportSeqID                VARCHAR(255),
    Div4WheelsOn                    VARCHAR(255),
    Div4TotalGTime                  VARCHAR(255),
    Div4LongestGTime                VARCHAR(255),
    Div4WheelsOff                   VARCHAR(255),
    Div4TailNum                     VARCHAR(255),
    Div5Airport                     VARCHAR(255),
    Div5AirportID                   VARCHAR(255),
    Div5AirportSeqID                VARCHAR(255),
    Div5WheelsOn                    VARCHAR(255),
    Div5TotalGTime                  VARCHAR(255),
    Div5LongestGTime                VARCHAR(255),
    Div5WheelsOff                   VARCHAR(255),
    Div5TailNum                     VARCHAR(255),
    NullV                           VARCHAR(255)
);
